# Generated by Django 4.0.2 on 2022-02-25 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableofcontentmodel',
            name='sub_section',
        ),
        migrations.AddField(
            model_name='tableofcontentmodel',
            name='parent_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tableofcontent_parent_section', to='demoapp_api.tableofcontentmodel'),
        ),
    ]
